/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{vue,js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container": "#eceeef",
                "on-error": "#ffffff",
                "secondary": "#48626e",
                "surface-container-low": "#f2f4f5",
                "on-tertiary": "#ffffff",
                "surface-bright": "#f8fafb",
                "outline": "#6f7979",
                "on-secondary-container": "#4e6874",
                "on-primary-container": "#006064",
                "on-secondary-fixed": "#021f29",
                "tertiary-fixed": "#ffdbc7",
                "on-tertiary-fixed": "#311300",
                "error-container": "#ffdad6",
                "on-surface-variant": "#3f4949",
                "secondary-container": "#cbe7f5",
                "primary-container": "#006064",
                "surface-variant": "#e1e3e4",
                "surface-container-high": "#e6e8e9",
                "inverse-surface": "#2e3132",
                "surface-container-lowest": "#ffffff",
                "on-surface": "#191c1d",
                "on-primary-fixed": "#002021",
                "error": "#ba1a1a",
                "primary": "#00464a",
                "on-primary-fixed-variant": "#004f53",
                "on-secondary": "#ffffff",
                "on-tertiary-fixed-variant": "#6b3a16",
                "tertiary-fixed-dim": "#ffb688",
                "inverse-primary": "#8ad3d7",
                "secondary-fixed-dim": "#afcbd8",
                "on-tertiary-container": "#ffbe95",
                "background": "#ffffff",
                "tertiary-container": "#7e4924",
                "primary-fixed": "#a6eff3",
                "on-secondary-fixed-variant": "#304a55",
                "on-error-container": "#93000a",
                "on-background": "#191c1d",
                "on-primary": "#ffffff",
                "surface-tint": "#14696d",
                "surface-dim": "#d8dadb",
                "surface": "#ffffff",
                "secondary-fixed": "#cbe7f5",
                "outline-variant": "#bec8c9",
                "surface-container-highest": "#e1e3e4",
                "tertiary": "#62330f",
                "primary-fixed-dim": "#8ad3d7",
                "inverse-on-surface": "#eff1f2"
            },
            fontFamily: {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" }
        },
    },
    plugins: [],
}
